using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MatchLogic.Application.Features.DataMatching.RecordLinkage
{
    public class CandidatePair
    {
        private readonly IRecordStore _store1;
        private readonly IRecordStore _store2;

        public Guid DataSource1Id { get; }
        public int Row1Number { get; }
        public Guid DataSource2Id { get; }
        public int Row2Number { get; }
        public double EstimatedSimilarity { get; init; }

        /// <summary>
        /// IDs of match definitions that generated this candidate pair
        /// </summary>
        public HashSet<Guid> MatchDefinitionIds { get; } = new();

        /// <summary>
        /// Comma-separated string of match definition IDs for easy serialization
        /// </summary>
        public string MatchDefinitionIdsString => string.Join(",", MatchDefinitionIds.Select(id => id.ToString("N")));

        public CandidatePair(
            Guid dataSource1Id, int row1Number,
            Guid dataSource2Id, int row2Number,
            IRecordStore store1, IRecordStore store2,
            double estimatedSimilarity = 0.0)
        {
            DataSource1Id = dataSource1Id;
            Row1Number = row1Number;
            DataSource2Id = dataSource2Id;
            Row2Number = row2Number;
            _store1 = store1;
            _store2 = store2;
            EstimatedSimilarity = estimatedSimilarity;
        }

        /// <summary>
        /// Add a match definition ID to this candidate
        /// </summary>
        public void AddMatchDefinition(Guid matchDefinitionId)
        {
            MatchDefinitionIds.Add(matchDefinitionId);
        }

        /// <summary>
        /// Add multiple match definition IDs to this candidate
        /// </summary>
        public void AddMatchDefinitions(IEnumerable<Guid> matchDefinitionIds)
        {
            foreach (var id in matchDefinitionIds)
            {
                MatchDefinitionIds.Add(id);
            }
        }

        /// <summary>
        /// Check if this candidate was generated by a specific match definition
        /// </summary>
        public bool HasMatchDefinition(Guid matchDefinitionId)
        {
            return MatchDefinitionIds.Contains(matchDefinitionId);
        }

        public virtual async Task<IDictionary<string, object>> GetRecord1Async() =>
            await _store1.GetRecordAsync(Row1Number);

        public virtual async Task<IDictionary<string, object>> GetRecord2Async() =>
            await _store2.GetRecordAsync(Row2Number);

        public async Task<(IDictionary<string, object>, IDictionary<string, object>)> GetRecordsAsync()
        {
            var task1 = _store1.GetRecordAsync(Row1Number);
            var task2 = _store2.GetRecordAsync(Row2Number);
            await Task.WhenAll(task1, task2);
            return (task1.Result, task2.Result);
        }

        /// <summary>
        /// Get records with match definition context for comparison service
        /// </summary>
        public async Task<CandidateWithRecords> GetRecordsWithContextAsync()
        {
            var (record1, record2) = await GetRecordsAsync();
            return new CandidateWithRecords
            {
                Record1 = record1,
                Record2 = record2,
                DataSource1Id = DataSource1Id,
                DataSource2Id = DataSource2Id,
                Row1Number = Row1Number,
                Row2Number = Row2Number,
                MatchDefinitionIds = new HashSet<Guid>(MatchDefinitionIds),
                EstimatedSimilarity = EstimatedSimilarity
            };
        }
    }
}
